[project]
name = "week-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic[dotenv]",
    "transformers",
    "pytest",
    "coverage",
    "ruff",
    "pre-commit"
]
